version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"